### ISSUE TITLE
"IMPORT FAILED"

### ISSUE THREAD

**Issue by DrZooDinghy** [GraftingRayman/ComfyUI_GraftingRayman#3]
I have a loading issue. When I open comfyui I get the following error:

> Traceback (most recent call last):
>   File "J:\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1864, in load_custom_node
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "J:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_GraftingRayman\__init__.py", line 1, in <module>
>     from .nodes import GRPromptSelector, GRImageResize, GRMaskResize, GRMaskCreate, GRMultiMaskCreate, GRImageSize, GRTileImage, GRPromptSelectorMulti, GRTileFlipImage, GRMaskCreateRandom, GRStackImage
>   File "J:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_GraftingRayman\nodes.py", line 9, in <module>
>     import httplib2
> ModuleNotFoundError: No module named 'httplib2'
> 
> Cannot import J:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_GraftingRayman module for custom nodes: No module named 'httplib2'
> 

I have installed httplib2 again but it didn't change anyting.
(pip3 install httplib2 --upgrade)

Thanks!

**Comment by GraftingRayman** [comment]
Hi DrZooDinghy

That should not even be there right now, been testing another node which needs it, but not on these

Updated the code to reflect
