### ISSUE TITLE
IMPORT FAILED: cannot import name 'packaging' from 'pkg_resources'

### ISSUE THREAD

**Issue by RGX650** [GraftingRayman/ComfyUI_GraftingRayman#6]
************************************
* Loading GraftingRaymans GR Nodes *
************************************
Traceback (most recent call last):
  File "C:\AI\COMFYUI\ComfyUI\nodes.py", line 1906, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\AI\COMFYUI\ComfyUI\custom_nodes\ComfyUI_GraftingRayman\__init__.py", line 5, in <module>
    from .Nodes.GRImage import GRImageSize, GRImageResize, GRStackImage, GRResizeImageMethods, GRImageDetailsDisplayer, GRImageDetailsSave, GRImagePaste, GRImagePasteWithMask
  File "C:\AI\COMFYUI\ComfyUI\custom_nodes\ComfyUI_GraftingRayman\Nodes\GRImage.py", line 12, in <module>
    from clip import tokenize, model
  File "C:\AI\COMFYUI\ComfyUI\venv\lib\site-packages\clip\__init__.py", line 1, in <module>
    from .clip import *
  File "C:\AI\COMFYUI\ComfyUI\venv\lib\site-packages\clip\clip.py", line 6, in <module>
    from pkg_resources import packaging
ImportError: cannot import name 'packaging' from 'pkg_resources' (C:\AI\COMFYUI\ComfyUI\venv\lib\site-packages\pkg_resources\__init__.py)

Cannot import C:\AI\COMFYUI\ComfyUI\custom_nodes\ComfyUI_GraftingRayman module for custom nodes: cannot import name 'packaging' from 'pkg_resources' (C:\AI\COMFYUI\ComfyUI\venv\lib\site-packages\pkg_resources\__init__.py)

**Comment by GraftingRayman** [comment]
Hi

Looks like you need to install packaging

Did not even know the nodes were using this

if you are using system python you can run "pip install packaging" of if you are running the portable version you can run the following in your comfyui folder .\python_embeded\python -m pip install packaging"

I will add this to the requirements file

**Comment by RGX650** [comment]
I have a the normal install of Comfyui (non portable)
I actually already have packaging installed... this is weird...

(venv) C:\AI\COMFYUI\ComfyUI\venv\Lib\site-packages>pip show packaging
Name: packaging
Version: 24.1
Summary: Core utilities for Python packages
Home-page:
Author:
Author-email: Donald Stufft <donald@stufft.io>
License:
Location: c:\ai\comfyui\comfyui\venv\lib\site-packages
Requires:
Required-by: accelerate, clip, datasets, docker, gunicorn, huggingface-hub, keras, kornia, lazy_loader, lightning, lightning-utilities, marshmallow, matplotlib, mlflow, mmcv-full, onnxruntime, onnxruntime-gpu, openxlab, pooch, pytest, pytorch-lightning, scikit-image, skypilot, tensorflow-intel, torchmetrics, transformers

**Comment by RGX650** [comment]
SOLVED !
pip install setuptools==69.5.1

https://stackoverflow.com/questions/78604018/importerror-cannot-import-name-packaging-from-pkg-resources-when-trying-to

**Comment by GraftingRayman** [comment]
added to requirements
