### ISSUE TITLE
GR Counter not working as expected

### ISSUE THREAD

**Issue by schoenid** [GraftingRayman/ComfyUI_GraftingRayman#7]
I've got the description from:
https://www.runcomfy.com/comfyui-nodes/ComfyUI_GraftingRayman/GR-Counter

The downloaded node works completely different - will say it's a completely different node.

Where can I get the node described above?
I simply want to count the iterations of batches, done by the `Empty Latent Image` node "Batch_size" option.

I've also tried to code it, but I don't understand the mechanisms behind.

**Comment by GraftingRayman** [comment]
Hi Schoenid, I don't know who created the profile on runcomfy.com but that is not what this node does
